version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            python -m tests.unit_tests

      #- run:
          #name: deploy to heroku
          #command: |
          #  git push https://heroku:$8332667f-53c0-4206-9fb4-94c970699691@git.heroku.com/$HEROKU_APP_NAME.git master
